### ISSUE TITLE
User's Feedback

### ISSUE THREAD

**Issue by rahulrahamanx** [Arun-TG/FeedbackBot#6]
It would be better if a user send massage through the feedback bot without typing /submit....
Its my request please remove that things..so user can easily send feedback..
Some of user not familiar to bot and not techy person..
Hope you understand what I'm trying to say.

**Comment by Arun-TG** [comment]
> It would be better if a user send massage through the feedback bot without typing /submit.... Its my request please remove that things..so user can easily send feedback.. Some of user not familiar to bot and not techy person.. Hope you understand what I'm trying to say.

Yes,
You're right!
I will look on it 👍

**Comment by Arun-TG** [comment]
> It would be better if a user send massage through the feedback bot without typing /submit.... Its my request please remove that things..so user can easily send feedback.. Some of user not familiar to bot and not techy person.. Hope you understand what I'm trying to say.

Yes,
You're right!
I will look on it 👍
